<?php 

function kaktarua_menu(){
	$items = array();
	
	/*$items['admin/kaktarua'] = array(
		'title'=>t('Kaktarua'),
		'description' => t('Enter menu links and title to list'),		
		'page callback' => 'kaktarua',		
		'access arguments' => array('access content'),
		'access callback' => 1,
		'file'=>'inc/kaktarua.inc',
		'type'=>MENU_NORMAL_ITEM,
		'weight' => 25
	);*/

	$items['admin/kaktarua'] = array(
		'title'=>t('Kaktarua'),
		'description' => t('Enter menu links and title to list'),		
		'page callback' => 'kaktarua',		
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
		'file'=>'inc/kaktarua.inc',
		'weight' => 25
	);

	return $items;
}
